import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { PizzaProvider } from "@/providers/PizzaContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" bg-gradient">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-fit  bg-gradient-to-br from-orange-400 to-red-600`}
      >
        <PizzaProvider>{children}</PizzaProvider>
        <Toaster />
      </body>
    </html>
  );
}
